// <auto-generated />
namespace Database_Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_sex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sex));
        
        string IMigrationMetadata.Id
        {
            get { return "201811071450058_add_sex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
